---
- hosts: all
  user: root
  
  vars:
     packages: ['software-properties-common', 'gnupg-curl' ]
     
  tasks:
  - name: Install the packages
    apt: name={{ item }} state=latest
    with_items: "{{ packages }}"
  
  - name: Install MariaDB repository
    apt_repository: 
      repo: deb https://mariadb.mirror.liquidtelecom.com/repo/10.5/ubuntu xenial main
      state: present
      
  - name: Add repository key to the system
    apt_key:
      url: https://ftp-master.debian.org/keys/archive-key-6.0.asc
      state: present
      
  - name: Update apt-get repo and cache
    apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
    
  - name: Install MariaDB Server
    apt: name=mariadb-server state=latest update_cache=yes
    
  - name: Install MariaDB Client
    apt: name=mariadb-client state=latest update_cache=yes
